export const NAMESPACE = 'ANDROID_SETTING_APP'
export const INFO = 'info'
export const GENERAL_SETTINGS = 'generalSettings'
export const SYNC_SETTINGS = 'synchronization'
export const ANALYTICS = 'analytics'
export const APPEARANCE = 'appearance'
export const PROGRAM_SETTINGS = 'program_settings'
export const DATASET_SETTINGS = 'dataSet_settings'
